[project]
name = "kit-esphome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "esphome>=2025.9.1",
    "pillow>=10.4.0",
    "platformio>=6.1.18",
]
